import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// define the metadata for the page
export const metadata: Metadata = {
  title: 'NextJS 13.4 Image Gallery',
  description: 'Generated by create next app',
}

// this is the root layout for the app
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
